/*
 * Jeremy Swanson
 * Property of / therein / so forth
 */
package views;

import utilities.NoDataException;
import baseclasses.Faculty;
import baseclasses.FacultyClass;
import baseclasses.OfferedClass;
import baseclasses.Person;
import java.awt.Component;
import java.util.ArrayList;
import utilities.Clearable;
import utilities.DataContainer;
import utilities.DateUtils;
import utilities.ModelMyList;
import utilities.RendererCourseList;
import utilities.FieldCheckable;

/**
 *
 * @author swans_000
 */
public class PanelNewTeacher extends javax.swing.JPanel implements Clearable, FieldCheckable {

    private DataContainer dc;
    /**
     * Creates new form NewTeacherPanel
     */
    public PanelNewTeacher() {
        initComponents();
        //myInitComponents();
    }
    public PanelNewTeacher(DataContainer data) {
        initComponents();
        dc = data;
        myInit();
    }    
    private void myInit() {
 
        // custom model for JList
        ModelMyList myModel = new ModelMyList(dc.getCourses());
        lstClasses.setModel(myModel);
        
        // Custom renderer for each list line
        lstClasses.setCellRenderer(new RendererCourseList());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radgrpStatus = new javax.swing.ButtonGroup();
        personPanel1 = new views.PanelPerson();
        lblDOH = new javax.swing.JLabel();
        lblDOT = new javax.swing.JLabel();
        lblSalary = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        radPT = new javax.swing.JRadioButton();
        radFT = new javax.swing.JRadioButton();
        lblStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClasses = new javax.swing.JList();
        lblClasses = new javax.swing.JLabel();
        txtDOH = new javax.swing.JFormattedTextField();
        txtDOT = new javax.swing.JFormattedTextField();
        txtSalary = new javax.swing.JFormattedTextField();
        lblDOHFormat = new javax.swing.JLabel();
        lblDOTFormat = new javax.swing.JLabel();

        lblDOH.setLabelFor(txtDOH);
        lblDOH.setText("Date of Hire:");

        lblDOT.setLabelFor(txtDOH);
        lblDOT.setText("Termination Date:");

        lblSalary.setLabelFor(txtSalary);
        lblSalary.setText("Salary:");

        btnAdd.setFont(new java.awt.Font("Aharoni", 0, 13)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 90, 150));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        radgrpStatus.add(radPT);
        radPT.setText("Part time");

        radgrpStatus.add(radFT);
        radFT.setText("Full time");

        lblStatus.setForeground(new java.awt.Color(255, 0, 0));
        lblStatus.setText("Status:");

        jScrollPane1.setViewportView(lstClasses);

        lblClasses.setLabelFor(lstClasses);
        lblClasses.setText("Courses:");

        txtDOH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        txtDOH.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));

        txtDOT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM/dd/yyyy"))));

        txtSalary.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        txtSalary.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.##"))));

        lblDOHFormat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblDOHFormat.setText("(MM/DD/YYYY)");

        lblDOTFormat.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblDOTFormat.setText("(MM/DD/YYYY)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(personPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lblDOH)
                                .addGap(27, 27, 27)
                                .addComponent(txtDOH, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(lblDOHFormat))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDOT)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSalary)
                                            .addComponent(lblStatus))))
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDOT, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(lblDOTFormat))
                                    .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(radFT)
                                        .addGap(13, 13, 13)
                                        .addComponent(radPT))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClasses)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(238, 238, 238))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDOH)
                            .addComponent(txtDOH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDOHFormat))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDOT)
                                .addGap(24, 24, 24)
                                .addComponent(lblSalary)
                                .addGap(24, 24, 24)
                                .addComponent(lblStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDOT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDOTFormat))
                                .addGap(18, 18, 18)
                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radFT)
                                    .addComponent(radPT))))))
                .addGap(4, 4, 4)
                .addComponent(lblClasses)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            checkFields();
            Faculty f = new Faculty();
        
            //Shared Person
            Person p = personPanel1.getPerson();
            f.setName(p.getName());
            f.setSocialSecurityNumber(p.getSocialSecurityNumber());
            f.setAddress(p.getAddress());
            f.setDateOfBirth(p.getDateOfBirth());
        
            // Faculty native values
            f.setDateOfHire(DateUtils.formattedTxtFld(txtDOH.getText()));
            f.setDateOfTermination(DateUtils.formattedTxtFld(txtDOT.getText()));
            f.setSalary(Double.parseDouble(txtSalary.getText().replaceAll(",", "")));
        
            // get radio button selection and set as Faculty.status
            char sel;
            if (radFT.isSelected()) {
                sel = 'F';
            } else if (radPT.isSelected()) {
                sel = 'P';
            } else {
                sel = '\0';
            }
            f.setStatus(sel);
        
            // Add classes from listbox
            ArrayList<FacultyClass> cllist = new ArrayList();        
            for (Object obj : lstClasses.getSelectedValuesList()) {
                OfferedClass oc = (OfferedClass)obj;
                FacultyClass fc = new FacultyClass(oc);
                cllist.add(fc);
            }
            f.setClasses(cllist);
        
            // add the object to the ArrayList, then clear the form
            if(WindowMain.dataBox.getFaculty().add(f) == true) {
                WindowMain.dataBox.hasNewData = true;
                clearData();
            }
        
            //System.out.println(WindowMain.dataBox.getFaculty().toString());
        } catch (NoDataException e) {
            e.promptForFields();
        } catch (NumberFormatException e) {
            NoDataException nde = new NoDataException("Salary");
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClasses;
    private javax.swing.JLabel lblDOH;
    private javax.swing.JLabel lblDOHFormat;
    private javax.swing.JLabel lblDOT;
    private javax.swing.JLabel lblDOTFormat;
    private javax.swing.JLabel lblSalary;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JList lstClasses;
    private views.PanelPerson personPanel1;
    private javax.swing.JRadioButton radFT;
    private javax.swing.JRadioButton radPT;
    private javax.swing.ButtonGroup radgrpStatus;
    private javax.swing.JFormattedTextField txtDOH;
    private javax.swing.JFormattedTextField txtDOT;
    private javax.swing.JFormattedTextField txtSalary;
    // End of variables declaration//GEN-END:variables

    @Override
    public void clearData() {
        personPanel1.clearData();
        txtDOH.setValue(null);
        txtDOT.setValue(null);
        txtSalary.setValue(null);
        radgrpStatus.clearSelection();
        lstClasses.clearSelection();
    }

    @Override
    public void checkFields() throws NoDataException {
        if (getMissingFields().size() > 0){
            throw new NoDataException(getMissingFields());
        }
            
    }
    
    public ArrayList<?> getMissingFields() {
        ArrayList<String> result = new ArrayList();
        
        if (txtSalary.getText().equals("")){
            result.add("Salary");
        }
        if (txtDOH.getText().length() == 0) {
            result.add("Date of Hire");
        }
        if (!radFT.isSelected() && !radPT.isSelected()){
            result.add("Status");
        }
        if (personPanel1.missingFields().size() > 0) {
            result.addAll(personPanel1.missingFields());
        }
        
        return result;
    }

    @Override
    public Component[] clearableItems() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
